export const groups = ['통계·매출','처방·치료','직원·운영'];
export const apps = [
 ['monthcheck.html','월별 체크','전월 대비 처방·검사·치료 변화',0],
 ['week.html','주간·월간 통계','내원·처방·매출 흐름 분석',0],
 ['sales-stats.html','매출 비교','요일·주·월별 매출 비교',0],
 ['bit-stats.html','비트 통계','비트 내원·처방 통계',0],
 ['ysarang-stats.html','의사랑 통계','의사랑 내원·처방 통계',0],
 ['ysarang-stats2.html','의사랑 통계 2','의사랑 상세 통계',0],
 ['bit-1visit.html','비트 초진 분석','초진 내원 분석',0],
 ['ysarang-1visit.html','의사랑 초진 분석','초진 내원 분석',0],
 ['ysarang-visit.html','내원경로','의사랑 일별·월별 내원경로',0],
 ['jinsul-map.html','내원 지도','주소별 신환·재진 내원 현황',0],
 ['jinsul-map update.html','내원 지도 · 별도 버전','기존 저장소의 별도 지도 버전',0],
 ['ysarang-Birthday.html','생일자 목록','만 18세 이상 월별 생일자 확인',0],
 ['blockcount.html','차단술 처방량','투여량·처방 횟수 분석',1],
 ['LAcord.html','2주 간격 조정 예상','PDNB·MBB·FJB 매출 변화 예상',1],
 ['ysarang-combination.html','신경차단술 조합','의사랑 조합별 통계·공통 수가',1],
 ['bit-block.html','비트 차단술','비트 차단술 분석',1],
 ['ysarang-block.html','의사랑 차단술','의사랑 차단술 분석',1],
 ['jinsul-treatment.html','치료유형 분석','주사·차단술·치료별 청구 분석',1],
 ['jinsul-Nonbenefit.html','비급여 치료 통계','리푸스·충격파·도수치료 통계',1],
 ['jinsul-strategy.html','비급여 분석·전략','치료별 분석과 운영 전략',1],
 ['jinsul-cord.html','묶음처방 시뮬레이터','묶음처방과 예상 금액',1],
 ['jinsul-schedule.html','근무일지','직원별 날짜·근무지 관리',2],
 ['jinsul-booking.html','일일수납대장 예약확인','월·주·일 예약구분 및 PT 처방 확인',2],
 ['pt_incentive.html','PT팀장 급여계산기','매출에 따른 인센티브 계산',2],
 ['jinsul_incentive.html','예약매칭 인센티브','예약·내원 매칭 분석',2],
 ['jinsul-edu.html','법정의무교육','의료기관 교육 안내',2],
 ['jinsul-Inspection.html','수납검수','수납일지와 OCS 마감 비교',2]
].map(([file,title,description,group])=>({file,title,description,group:groups[group]}));
