import test from 'node:test';
import assert from 'node:assert/strict';
import worker,{digest,passwordHash} from '../worker.mjs';
import {database} from './database.mjs';
const origin='https://portal.example';
function fixture(){const env={DB:database(),PASSWORD_PEPPER:'test-pepper-'.repeat(5),BOOTSTRAP_TOKEN:'test-bootstrap-token',ASSETS:{fetch:async request=>new Response('asset:'+new URL(request.url).pathname,{headers:{'Content-Type':'text/html'}})}};const request=(path,data,cookie,extra={})=>worker.fetch(new Request(origin+path,{method:data===undefined?'GET':'POST',headers:{Origin:origin,...(cookie?{Cookie:cookie}:{}),...extra},body:data===undefined?undefined:JSON.stringify(data)}),env);return {env,request};}
const password='Strong-test-password-123';
async function bootstrap(f){assert.equal((await f.request('/api/bootstrap',{token:'test-bootstrap-token',username:'owner',name:'관리자',password})).status,200);}
async function login(f,username='owner',value=password){const response=await f.request('/api/login',{username,password:value});assert.equal(response.status,200);return response.headers.get('Set-Cookie').split(';')[0];}
async function employee(f,admin,username='staff'){assert.equal((await f.request('/api/users',{username,name:'직원',password,role:'staff',permissions:['통계·매출']},admin)).status,201);return f.env.DB.prepare('SELECT * FROM users WHERE username=?').bind(username).first();}
test('unauthenticated direct HTML, data and catalog requests are blocked',async()=>{const f=fixture();for(const path of ['/','/monthcheck.html','/hira-prices.json','/catalog.json','/admin.html']){const response=await f.request(path);assert.equal(response.status,302);assert.equal(response.headers.get('Location'),'/login.html');}assert.equal((await f.request('/api/users')).status,401);assert.equal((await f.request('/login.html')).status,200);});
test('fail closed when server secrets are missing',async()=>{const f=fixture();delete f.env.PASSWORD_PEPPER;assert.equal((await f.request('/monthcheck.html')).status,503);});
test('cross-origin or missing-origin mutations are rejected',async()=>{const f=fixture();assert.equal((await f.request('/api/login',{},null,{Origin:'https://other.example'})).status,403);assert.equal((await worker.fetch(new Request(origin+'/api/login',{method:'POST',body:'{}'}),f.env)).status,403);});
test('bootstrap requires a secret and cannot replace first admin',async()=>{const f=fixture();assert.equal((await f.request('/api/bootstrap',{token:'wrong'})).status,403);await bootstrap(f);assert.equal((await f.request('/api/bootstrap',{token:'test-bootstrap-token',username:'second',name:'다른 관리자',password})).status,409);assert.equal(f.env.DB.raw.prepare('SELECT COUNT(*) AS n FROM users').get().n,1);});
test('password hashes use different salts and do not store plain text',async()=>{const f=fixture();await bootstrap(f);const user=await f.env.DB.prepare('SELECT * FROM users').first();assert.notEqual(user.password_hash,password);assert.equal(user.password_hash,await passwordHash(password,user.salt,f.env.PASSWORD_PEPPER));assert.notEqual(await passwordHash(password,'other-salt',f.env.PASSWORD_PEPPER),user.password_hash);});
test('login returns a secure cookie and hashed server session; logout revokes it',async()=>{const f=fixture();await bootstrap(f);const response=await f.request('/api/login',{username:'owner',password});const full=response.headers.get('Set-Cookie');for(const value of ['HttpOnly','Secure','SameSite=Strict','Path=/'])assert.ok(full.includes(value));const cookie=full.split(';')[0];const token=cookie.split('=')[1];assert.equal((await f.env.DB.prepare('SELECT * FROM sessions').first()).token_hash,await digest(token));assert.equal((await f.request('/api/me',undefined,cookie)).status,200);assert.equal((await f.request('/api/logout',{},cookie)).status,200);assert.equal((await f.request('/api/me',undefined,cookie)).status,401);});
test('temporary passwords require change before any work or admin endpoint',async()=>{const f=fixture();await bootstrap(f);const admin=await login(f);await employee(f,admin);const staff=await login(f,'staff');assert.equal((await f.request('/monthcheck.html',undefined,staff)).headers.get('Location'),'/account.html');assert.equal((await f.request('/api/catalog',undefined,staff)).status,403);for(const path of ['/account.html','/account.js','/portal.js'])assert.equal((await f.request(path,undefined,staff)).status,200);assert.equal((await f.request('/api/password',{current:password,password:'Replacement-password-123'},staff)).status,200);assert.equal((await f.request('/api/me',undefined,staff)).status,401);const fresh=await login(f,'staff','Replacement-password-123');assert.equal((await f.request('/monthcheck.html',undefined,fresh)).status,200);assert.equal((await f.request('/jinsul-schedule.html',undefined,fresh)).status,403);assert.equal((await f.request('/admin.html',undefined,fresh)).status,403);assert.equal((await f.request('/api/users',undefined,fresh)).status,403);const {apps}=await (await f.request('/api/catalog',undefined,fresh)).json();assert.ok(apps.every(a=>a.group==='통계·매출'));});
test('account suspension immediately revokes sessions and prevents login',async()=>{const f=fixture();await bootstrap(f);const admin=await login(f),user=await employee(f,admin),staff=await login(f,'staff');assert.equal((await f.request('/api/users/'+user.id,{name:'직원',role:'staff',permissions:[],active:false},admin)).status,200);assert.equal((await f.request('/api/me',undefined,staff)).status,401);assert.equal((await f.request('/api/login',{username:'staff',password})).status,401);});
test('administrator reset invalidates old passwords and sessions',async()=>{const f=fixture();await bootstrap(f);const admin=await login(f),user=await employee(f,admin),staff=await login(f,'staff');assert.equal((await f.request('/api/users/'+user.id+'/reset',{password:'Reset-password-123456'},admin)).status,200);assert.equal((await f.request('/api/me',undefined,staff)).status,401);assert.equal((await f.request('/api/login',{username:'staff',password})).status,401);const fresh=await login(f,'staff','Reset-password-123456');assert.equal((await (await f.request('/api/me',undefined,fresh)).json()).user.mustChange,true);});
test('admin cannot suspend or demote own account; invalid roles and empty passwords rejected',async()=>{const f=fixture();await bootstrap(f);const admin=await login(f),user=await f.env.DB.prepare('SELECT * FROM users').first();assert.equal((await f.request('/api/users/'+user.id,{name:'관리자',role:'staff',permissions:[],active:true},admin)).status,400);assert.equal((await f.request('/api/users',{username:'test',name:'직원',password:'',role:'staff',permissions:[]},admin)).status,400);assert.equal((await f.request('/api/users',{username:'test',name:'직원',password,role:'superuser',permissions:[]},admin)).status,400);});
test('expired and idle sessions are rejected',async()=>{const f=fixture();await bootstrap(f);let cookie=await login(f);f.env.DB.raw.exec('UPDATE sessions SET last_seen=0');assert.equal((await f.request('/api/me',undefined,cookie)).status,401);cookie=await login(f);f.env.DB.raw.exec('UPDATE sessions SET expires_at=0');assert.equal((await f.request('/api/me',undefined,cookie)).status,401);});
test('login rate limiting cannot be bypassed by changing IP for same user',async()=>{const f=fixture();for(let n=0;n<10;n++)assert.equal((await f.request('/api/login',{username:'unknown',password},null,{'CF-Connecting-IP':'192.0.2.'+n})).status,401);assert.equal((await f.request('/api/login',{username:'unknown',password},null,{'CF-Connecting-IP':'192.0.2.100'})).status,429);});
test('unknown paths never expose source or configuration; responses prevent caching',async()=>{const f=fixture();await bootstrap(f);const admin=await login(f);for(const path of ['/worker.mjs','/wrangler.jsonc','/.dev.vars','/migrations/0001_accounts.sql'])assert.equal((await f.request(path,undefined,admin)).status,404);assert.equal((await f.request('/monthcheck.html',undefined,admin)).headers.get('Cache-Control'),'no-store');});

test('short and longer passwords work while empty passwords are rejected',async()=>{const f=fixture();await bootstrap(f);const admin=await login(f);for(const [i,value] of ['a','x'.repeat(200)].entries()){assert.equal((await f.request('/api/users',{username:'test'+i,name:'직원',password:value,role:'staff',permissions:[]},admin)).status,201);await login(f,'test'+i,value);}});
test('admin menu edits persist, reject stale updates and preserve access groups',async()=>{const f=fixture();await bootstrap(f);const admin=await login(f);const {menu}=await(await f.request('/api/menu',undefined,admin)).json();menu.categories[0].name='새 분류';menu.apps[0].title='새 업무';menu.apps[0].note='<script>plain text</script>';assert.equal((await f.request('/api/menu',{menu,revision:0},admin)).status,200);assert.equal((await f.request('/api/menu',{menu,revision:0},admin)).status,409);menu.apps[0].description='두 번째 수정';assert.equal((await f.request('/api/menu',{menu,revision:1},admin)).status,200);const catalog=await(await f.request('/api/catalog',undefined,admin)).json();assert.equal(catalog.apps[0].title,'새 업무');assert.equal(catalog.apps[0].group,'통계·매출');assert.equal(catalog.apps[0].categoryName,'새 분류');menu.apps[0].file='../worker.mjs';assert.equal((await f.request('/api/menu',{menu,revision:2},admin)).status,400);await employee(f,admin);const staff=await login(f,'staff');assert.equal((await f.request('/api/password',{current:password,password:'new'},staff)).status,200);const fresh=await login(f,'staff','new');assert.equal((await f.request('/api/menu',undefined,fresh)).status,403);assert.equal((await f.request('/api/menu',{menu,revision:2},fresh)).status,403);});

test('workspace returns identity and allowed menu in one authenticated request',async()=>{const f=fixture();await bootstrap(f);const admin=await login(f);const result=await(await f.request('/api/workspace',undefined,admin)).json();assert.equal(result.user.role,'admin');assert.ok(result.apps.length>0);assert.ok(result.categories.length>0);assert.equal((await f.request('/api/workspace')).status,401);});
test('rapid navigation avoids redundant session writes and data remains uncached',async()=>{const f=fixture();await bootstrap(f);const admin=await login(f);let writes=0;const prepare=f.env.DB.prepare.bind(f.env.DB);f.env.DB.prepare=sql=>{if(sql.startsWith('UPDATE sessions SET last_seen'))writes++;return prepare(sql);};for(let i=0;i<5;i++)assert.equal((await f.request('/api/me',undefined,admin)).status,200);assert.equal(writes,0);assert.equal((await f.request('/api/workspace',undefined,admin)).headers.get('Cache-Control'),'no-store');assert.equal((await f.request('/shell.js',undefined,admin)).headers.get('Cache-Control'),'private, max-age=0, must-revalidate');assert.equal((await f.request('/hira-prices.json',undefined,admin)).headers.get('Cache-Control'),'no-store');});
test('versioned static assets reuse browser cache without caching protected data',async()=>{const f=fixture();await bootstrap(f);const admin=await login(f);for(const asset of ['/shell.js','/design.css','/xlsx.full.min.js'])assert.equal((await f.request(asset+'?v=0123456789abcdef',undefined,admin)).headers.get('Cache-Control'),'private, max-age=86400, immutable');assert.equal((await f.request('/shell.js?v=0123456789abcdef')).status,302);for(const path of ['/api/workspace','/hira-prices.json','/bit-stats.html'])assert.equal((await f.request(path+'?v=0123456789abcdef',undefined,admin)).headers.get('Cache-Control'),'no-store');});
